apiVersion: apps/v1
kind: deployment
metadata:
  name: frontend
  labels: # these are the replicaset lables.
    app: nginix
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector: 
  # these are used to select the pod to create replices.
  matchLabels:
      tier: frontend
      app: nginx
  # this is pod definition
  template: 
    metadata:
    # this labes belongs to pod.
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion}}